[package]

name = "tiled"
version = "0.9.5"
description = "A rust crate for loading in maps created by the Tiled editor"
repository = "https://github.com/mattyhall/rs-tiled.git"
# documentation = "http://rust-ci.org/mattyhall/rs-tiled/doc/tiled/"
readme = "README.md"
license = "MIT"
authors = ["Matthew Hall <matthew@quickbeam.me.uk>"]
edition = "2018"

keywords = ["tiled", "tmx", "map"]

[features]
default = ["zstd"]

[lib]
name = "tiled"
path = "src/lib.rs"

[[example]]
name = "example"
path = "examples/main.rs"

[[example]]
name = "sfml"
path = "examples/sfml/main.rs"

[dependencies]
base64  = "0.10"
xml-rs  = "0.8"
libflate = "0.1.18"
zstd = { version = "0.9", optional = true }

[dev-dependencies.sfml]
git = "https://github.com/jeremyletang/rust-sfml"
features = ["graphics"]
rev = "19b5e1082fbb58d7c1646eef32cb6fd01353c9d3"